language: objective-c
podfile: Example/Podfile
osx_image: xcode8
before_install:
- gem install cocoapods
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -workspace Example/GTToast.xcworkspace -scheme GTToast-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
